spring.application.name=debug-app

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/debug_app
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
